### ISSUE TITLE
Decoding issues when working with enterprise.lemmy.ml

### ISSUE THREAD

**Issue by ckaik** [rrainn/Lemmy-Swift-Client#14]
I've been trying out this client with the enterprise.lemmy.ml instance which is listed [here](https://join-lemmy.org/docs/en/contributors/04-api.html) as a lemmy instance for testing purposes.

I haven't gotten far but I did run into some issues when sending `GetSiteRequest` and I figured I'd check in before doing work and submitting a PR for this since I'm not entirely sure if these issues even _should_  be handled.

Here's what I've run into when running sending a `GetSiteRequest` to https://enterprise.lemmy.ml/api/v3:

1. On that instance the `admins` seem to be missing an `inbox_url` in their `PersonSafe`. Which is correctly implemented by Lemmy-Swift-Client since according to the documentation, `inbox_url` is _not_ optional. However since it's missing there's no way to work with that instance. [Documentation](https://join-lemmy.org/api/interfaces/PersonSafe.html#inbox_url)
2. The same is true for `GetSiteResponse` and its `online` property, which is also missing on that instance. [Documentation](https://join-lemmy.org/api/interfaces/GetSiteResponse.html#online)
3. And finally for the `federation_debug` property on `LocalSite`. [Documentation](https://join-lemmy.org/api/interfaces/LocalSite.html#federation_debug)

There's one more issue though about the `RegistrationMode` enum, used for the `registration_mode` property on `LocalSite`. Currently the `.open` has the string value of `open`. However in this specific instance the server actually returns `Open` and therefore decoding fails.

E.g. adding a custom decoding initializer to `RegistrationMode` fixes the issue.

```swift
public init(from decoder: Decoder) throws {
	let container = try decoder.singleValueContainer()
	let value = try container.decode(String.self)

	guard let mode = RegistrationMode(rawValue: value.lowercased()) else {
		throw DecodingError.dataCorrupted(.init(
			codingPath: decoder.codingPath,
			debugDescription: "could not extract registration mode"
		))
	}

	self = mode
}
```
Note: this does have the caveat of requiring rawValues for all cases to be fully lowercased.

I guess this is a question of Accuracy vs Compatibility.

**Comment by fishcharlie** [comment]
@ckaik This is a tough one. I tend to think that we shouldn't support these super custom versions of Lemmy. The Lemmy developers have an obligation to ensure backwards compatibility with their API, and do a good job at communicating those changes.

I'm not trying to throw shade here. Their project has grown massively over the past few weeks/months, and I'm sure they are doing everything they can to even keep their heads above water.

That being said, I'm not sure why it should fall on this project to chase undocumented compatibility with unreleased versions. For all we know we could make these changes in our library, and then they revert the change in enterprise.lemmy.ml.

Ideally, Lemmy would bump the API version number from `v3` to `v4` before making these breaking changes or something.

We are kinda at the mercy of the platform here. And while I do really support compatibility, and I want this library to work with Lemmy in general, supporting undocumented unreleased compatibility feels a bridge too far here.

I'd encourage you to create an issue on Lemmy's repo, explaining the differences you found in the documentation and link it here. I'd be curious to hear what the Lemmy developers have to say about this.

**Comment by ckaik** [comment]
Fully agree.

I checked out the Go client and from the code it looks like it's working pretty much the same as this one.

One small question remains, what kind of instance do you test with... do you use an instance running in prod, are you running your own locally?

**Comment by fishcharlie** [comment]
@ckaik I'm testing against my prod instance currently (eventfrontier.com). Eventually for more complicated things I'm gonna setup a local instance to test against. But the requests I'm working on now are mainly retrieving data, so I'm not too worried about testing against prod for now.
