### ISSUE TITLE
Support Lemmy v0.18.0

### ISSUE THREAD

**Issue by fishcharlie** [rrainn/Lemmy-Swift-Client#19]
[Lemmy v0.18.0 was released](https://join-lemmy.org/news/2023-06-23_-_Lemmy_Release_v0.18.0) today.

According to the post:

- There are two breaking changes since the last release:
    - [GetSite.taglines](https://join-lemmy.org/api/interfaces/GetSiteResponse.html#taglines) is now required, and is an empty array.
    - `SortType` and `ListingType` are now numbered enums, rather than strings in some places, and numbers in others.

A full comparison of the changes can be found [here](https://github.com/LemmyNet/lemmy-js-client/compare/0.17.0-rc.1...0.18.0-rc.1).

It is very unclear at this point how the Lemmy API is versioned. The expectation (although I don't believe documented anywhere) is that breaking API changes would bump the version in the API path. This was not the case with the release of Lemmy 0.18.0.

I have posted a [comment](https://eventfrontier.com/comment/3887) in reply to @dessalines's Lemmy post requesting clarification on how Lemmy is viewing API versioning.

An API like this that is designed to be used externally, needs some type of solid versioning system, because you don't know what server you are talking to and what version they are running until you run GetSiteRequest.

---

I'm still trying to figure out the best way to handle these breaking changes within this package. If anyone has any feedback or advice, I would love to hear it.

**Comment by ckaik** [comment]
I generally agree, this isn't great to work with.

On the other hand they're at 0.x releases so technically breaking changes can come at any time. _Still_, this isn't optimal.

It's basically impossible to predict or handle these changes in a way that wouldn't require an update to this API Client and that is not a great situation for people relying on this to build an app.
