### ISSUE TITLE
Non-string types are not included in the URL parameters for GET requests

### ISSUE THREAD

**Issue by mdhiggins** [rrainn/Lemmy-Swift-Client#2]
Started playing around with this API tonight and noticed an issue

Any parameter from any of the Codable objects that's not a string is not included in the queryItems for the URLRequest

The issue comes from this code
https://github.com/rrainn/Lemmy-Swift-Client/blob/57aba1d4b642882b34089017342f3b5c103f5a83/Sources/Lemmy-Swift-Client/Lemmy_Swift_Client.swift#L19-L23

Casting the value as String always returns nil for all the datatypes that aren't a String (int/enums, etc)

This gets a little more annoying to fix too as Mirror returns non-nil value even when nil so using `String(describing: value)` doesn't work either

One option would be to cast to `CustomStringConvertible` but you would also need to make all your enums conform to this protocol to work, which I guess wouldn't be that difficult

The other option which is working in my quick testing is to just serialize it to JSON and then use String(describing: value) like this

```swift
			request.url = request.url?.appending(queryItems: mirror.children.compactMap { (label, value) in
			let encoder = JSONEncoder()
			if let data = try? encoder.encode(apiRequest), let jsonObject = try? JSONSerialization.jsonObject(with: data, options: []), let parameters = jsonObject as? [String: Any?] {
				request.url = request.url?.appending(queryItems: parameters.compactMap { key, value in
					guard let value else { return nil }
					return URLQueryItem(name: key, value: String(describing: value))
				})
			}
```

Happy to put together a pull request for either approach

**Comment by fishcharlie** [comment]
@mdhiggins First of all thanks for checking out this library! Really appreciate the feedback and offer to help with PRs.

This was such an oversight on my end.

For performance reasons, I lean towards the `CustomStringConvertible` option. Encoding into JSON just to convert to a dictionary feels wasteful and not very performant.

But beyond that consideration, I think I'm good with either option.

A PR would be greatly appreciated.

**Comment by mdhiggins** [comment]
Potentially can be closed with https://github.com/rrainn/Lemmy-Swift-Client/pull/4
