### ISSUE TITLE
Error Handling 

### ISSUE THREAD

**Issue by gibbiemonster** [rrainn/Lemmy-Swift-Client#21]
Hi there!

I am building a Lemmy client for macOS using this package. (awesome work, by the way!!)

The only problem is, I cannot find out how to handle errors properly. This is what I have now:
```swift
    func login(username: String, password: String) async throws -> LoginResponse {
        var req = LoginRequest(username_or_email: username, password: password)
        if let response = try? await api.request(req) {
            UserDefaults.standard.set("LoggedIN", forKey: "login_temp") // Temporary Placeholder
            return response
        } else {
            throw LoginError(message: "Login failed: Check your username and password") // see footnote
        }
    }
```
[^1]

I really don't like using functions with `throws` - it just complicates things in my opinion. Is there another way?

Thanks!

[^1]: LoginError is a simple struct with a `message` key as a string, which extends to error.

**Comment by fishcharlie** [comment]
@blockarchitech What exactly is the problem with the code you posted?

**Comment by fishcharlie** [comment]
Closing as stale due to no reply from the original author.
