### ISSUE TITLE
keyNotFound when calling GetPostsRequest()

### ISSUE THREAD

**Issue by Neufunk** [rrainn/Lemmy-Swift-Client#29]
I get this error when calling GetPostsRequest() in my attempts to build a Feed :

_Unexpected error getting feed: keyNotFound(CodingKeys(stringValue: "inbox_url", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "posts", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "creator", intValue: nil)], debugDescription: "No value associated with key CodingKeys(stringValue: \"inbox_url\", intValue: nil) (\"inbox_url\").", underlyingError: nil))._

There is no way to pass the "inbox_url" parameter in the GetPostRequest struct.

**Comment by fishcharlie** [comment]
@Neufunk Fixed in #22. I'm hoping to do a release soon, but in the meantime you can just point to the `main` branch.
