### ISSUE TITLE
Consideration: Make all data types conform to Hashable

### ISSUE THREAD

**Issue by creekdrops** [rrainn/Lemmy-Swift-Client#31]
This might already be something already being considered and worked on, but I figured I would weigh in if not. As of right now, not having types such as PostView, CommentView, etc. conform to hashable can be a bit limiting for iteration and usage within the NavigationStack. I'm willing to take this on and commit, but I wanted to get your guys thoughts before doing so.

**Comment by fishcharlie** [comment]
@creekdrops I'm all for it. Feel free to make a PR.

**Comment by creekdrops** [comment]
@fishcharlie PR is available [here](https://github.com/rrainn/Lemmy-Swift-Client/pull/36). Let me know if you have any suggestions or feedback. 😄
